/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.4.2, using .NET Server 2.4.0 template (version 2)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
**
**     Generated by banerjeesuprateek <Suprateek.Banerjee@thi.de>
** </auto-generated>
**
** Copyright (c) 2006-2017 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.5
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.5, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://thi.opcua.hl7.org/opcfhir/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.5/
**
** Created: 01.09.2017
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.IO;
using System.Reflection;
using UnifiedAutomation.UaBase;
using UnifiedAutomation.UaServer;


namespace thi.opcfhir
{
    internal partial class opcfhirNodeManager : BaseNodeManager
    {
        #region Constructor
        /// <summary>
        /// Initializes a new instance of the class.
        /// </summary>
        public opcfhirNodeManager(ServerManager server) : base(server)
        {
        }
        #endregion

        #region IDisposable
        /// <summary>
        /// An overrideable version of the Dispose.
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // TBD
            }
        }
        #endregion

        #region Overridden Methods
        /// <summary>
        /// Called when the node manager is started.
        /// </summary>
        public override void Startup()
        {
            try
            {
                Console.WriteLine("Starting opcfhirNodeManager.");

                DefaultNamespaceIndex = AddNamespaceUri("http://thi.opcua.hl7.org/opcfhir/");

                Console.WriteLine("Loading the opcfhir Model.");
                ImportUaNodeset(Assembly.GetEntryAssembly(), "opcfhir.xml");
                NodeId systolicNodeId = new NodeId(6037, 2);
                NodeId diastolicNodeId = new NodeId(6044, 2);
                systolicNode = FindInMemoryNode(systolicNodeId) as VariableNode;
                GetNodeHandle(Server.DefaultRequestContext, systolicNodeId, Attributes.Value, out sysHandle);
                diastolicNode = FindInMemoryNode(diastolicNodeId) as VariableNode;
                GetNodeHandle(Server.DefaultRequestContext, diastolicNodeId, Attributes.Value, out diaHandle);
                simTimer = new Timer(SimulateValues, null,1500,Timeout.Infinite);
                
            }
            catch (Exception e)
            {
                Console.WriteLine("Failed to start opcfhirNodeManager " + e.Message);
            }
        }

        private void SimulateValues(Object o)
        {
           
            Random random = new Random();
            int randomNumber = random.Next(90, 220);
            systolicNode.Value = new Variant(randomNumber);
            randomNumber = random.Next(50, 120);
            diastolicNode.Value = new Variant(randomNumber);
            simTimer.Change(1500, Timeout.Infinite);
            this.ReportDataChanges(Server.DefaultRequestContext, sysHandle);
            this.ReportDataChanges(Server.DefaultRequestContext, diaHandle);

        }

        /// <summary>
        /// Called when the node manager is stopped.
        /// </summary>
        public override void Shutdown()
        {
            try
            {
                Console.WriteLine("Stopping opcfhirNodeManager.");

                // TBD
            }
            catch (Exception e)
            {
                Console.WriteLine("Failed to stop opcfhirNodeManager " + e.Message);
            }
        }
        #endregion

        #region Private Methods
        #endregion

        #region Private Fields
        private VariableNode systolicNode;
        private VariableNode diastolicNode;
        private NodeAttributeHandle sysHandle;
        private NodeAttributeHandle diaHandle;
        private Timer simTimer;
        #endregion
    }
}

